### ISSUE TITLE
可否解释下这段代码含义，为何要加 0.5

### ISSUE THREAD

**Issue by Frisco22** [lizhuoyuan/ReactNativeScreenUtil#2]
export const scaleSize = (size: Number) => {
  let scaleWidth = screenW / w2
  let scaleHeight = screenH / h2
  let scale = Math.min(scaleWidth, scaleHeight)
  size = Math.round((size * scale + 0.5))
  return size / DEFAULT_DENSITY
}

**Comment by lizhuoyuan** [comment]
向上取整

**Comment by Frisco22** [comment]
为何要向上取整？或者请解释下这段代码，感谢

**Comment by lizhuoyuan** [comment]
首先算出缩放比例 . 然后以最小的为准
然后计算应该显示的大小,参数为基准设计中的尺寸
加0.5是是为了向上取整, 假如你有个尺寸显示是0.49, 直接四舍五入这个东西就没了  所以+0.5

**Comment by Frisco22** [comment]
嗯嗯还有一个疑问，缩放比例为什么以最小的为基准啊

**Comment by lizhuoyuan** [comment]
防止尺寸过大
