### ISSUE TITLE
用户设置系统文字大小为大 会有问题

### ISSUE THREAD

**Issue by lp4298707** [lizhuoyuan/ReactNativeScreenUtil#4]
如果用户设置系统文字大小为大 字体会变化 导致布局有问题,请问有办法解决这个问题吗? AlowFontScale为fales没效果

**Comment by lizhuoyuan** [comment]
```
/**
 * 设置字体的size（单位px）
 * @param size 传入设计稿上的px
 * @returns {Number} 返回实际sp ,会随系统缩放比例改变，如不需要请去掉 * fontScale
 */
export function setSpText(size: Number) {
    const scale = Math.min(_scaleWidth, _scaleHeight);
    return size * scale * fontScale;
}
```
把这个方法中的
```
 return size * scale * fontScale;
```
改成
```
return size * scale
```

**Comment by lp4298707** [comment]
/**
 * 屏幕工具类
 * ui设计基准,iphone 6
 * width:750
 * height:1334
 */

/*
 设备的像素密度，例如：
 PixelRatio.get() === 1          mdpi Android 设备 (160 dpi)
 PixelRatio.get() === 1.5        hdpi Android 设备 (240 dpi)
 PixelRatio.get() === 2          iPhone 4, 4S,iPhone 5, 5c, 5s,iPhone 6,xhdpi Android 设备 (320 dpi)
 PixelRatio.get() === 3          iPhone 6 plus , xxhdpi Android 设备 (480 dpi)
 PixelRatio.get() === 3.5        Nexus 6
*/

import {
	Dimensions,
	PixelRatio,
} from 'react-native';

//设备的宽度
export const deviceWidth = Dimensions.get('window').width;
//设备的高度
export const deviceHeight = Dimensions.get('window').height;
//返回字体大小缩放比例
let fontScale = PixelRatio.getFontScale();
//当前设备的像素密度
let pixelRatio = PixelRatio.get();
/*
	iphone6 的像素密度
	因为一般的设计稿都是以 iphone6 为基础来设计的，所以这里以 iPhone6 为基础写这个工具类，当然如果你的不是，可以在上面更改，defaultPixel 改成你用的设备像素就好了。
*/
const defaultPixel = 2;
//px转换成dp
const w2 = 750 / defaultPixel;
const h2 = 1334 / defaultPixel;
//获取缩放比例
const scale = Math.min(deviceHeight / h2, deviceWidth / w2);
/**
 * 设置text为sp
 * @param size sp
 * return number dp
 */
export function setSpText(size: number) {
	return scaleSize(size)
}

export function scaleSize(size: number) {
	size = Math.round(size * scale + 0.5);
	return size / defaultPixel;
}





我现在用的应该是你的早期版本,我在现在项目中可以直接把新版本复制过来替换了吗?

**Comment by lizhuoyuan** [comment]
因为适配方法改了 不确定效果如何 ， 建议你先备份一下当前可以用的版本，然后用新版试试 
如果有问题可以继续联系我

**Comment by lp4298707** [comment]
ok  非常感谢

**Comment by lp4298707** [comment]
你好  我还是用的早期版本,  但是我把fontScale 删除了 直接 

export function setSpText(size: number) {
     return scaleSize(size)
}  

字体还是会变大  但是不像原来那么大了,只是大一点点,  不大明白是什么原因造成的

**Comment by lizhuoyuan** [comment]
allowFontScaling 没有理由不管用啊。。
我之前的项目用这个属性是可以控制的，
我又试了一下：
![image](https://user-images.githubusercontent.com/15923901/46990489-17a51700-d134-11e8-8e39-196f17c38722.png)
![image](https://user-images.githubusercontent.com/15923901/46990500-255a9c80-d134-11e8-81bb-d370b1f2661c.png) 

![image](https://user-images.githubusercontent.com/15923901/46990689-20e2b380-d135-11e8-9a55-8a313c0cb820.png)
![image](https://user-images.githubusercontent.com/15923901/46990697-2b04b200-d135-11e8-9128-953d0352ea92.png)


 加了这个属性之后，字体没有随着系统变大 后两张对比应该比较清晰

**Comment by lp4298707** [comment]
![qq 20181016111959](https://user-images.githubusercontent.com/38391864/46990916-0ceb8180-d136-11e8-98b2-903d7c3170f1.png)



![qq 20181016111913](https://user-images.githubusercontent.com/38391864/46990844-bed67e00-d135-11e8-8544-32544e7120ac.png)
上面是没有开大号字体  下面是开了大号字体,   搞不懂是为什么........

**Comment by lizhuoyuan** [comment]
不确定你的原因，
改成这个试一下吧
/*

设置text为sp
@param size sp
return number dp
*/
export function setSpText(size: number) {
return scaleSize(size)/fontScale 
}

**Comment by lp4298707** [comment]
改成这个就可以啦  ,  哇.....   搞不懂..........

**Comment by lp4298707** [comment]
但是  正常模式下  字体变小了  T.T

**Comment by lizhuoyuan** [comment]
看起来是allowFontScaling  没有效果，原因不明。
改成这个是把字体大小除以了缩放比例。
你可以打印一下看你不同字体大小时候，缩放比例是多少

**Comment by lp4298707** [comment]
刚才正常模式下字体变小是因为我改了字体之后没有刷新  我刷新之后就好了 应该是没问题的  谢谢大神!
