### ISSUE TITLE
引入报错

### ISSUE THREAD

**Issue by dafuchixigua** [lizhuoyuan/ReactNativeScreenUtil#5]
![qq 20181124104152](https://user-images.githubusercontent.com/42792604/48963794-99ab1a00-efd5-11e8-881e-b7328416c9e0.png)
![qq 20181124104228](https://user-images.githubusercontent.com/42792604/48963798-a92a6300-efd5-11e8-9cbd-b4a9a664792c.png)

**Comment by lizhuoyuan** [comment]
引入方式可能不对
import * as ScreenUtil from '路径'
