### ISSUE TITLE
安卓有误差

### ISSUE THREAD

**Issue by EliYenn** [lizhuoyuan/ReactNativeScreenUtil#6]
高度在安卓上有误差

**Comment by Eruich** [comment]
安卓：绝对定位好像不适用，同样的值，不同屏幕下位置不一致

**Comment by lizhuoyuan** [comment]
@15914038396  高度可以使用setWidth , 只有在高度上需要匹配屏幕高度进行缩放才使用setHeight(不知道你是不是因为这个原因导致的问题)

@Eruich  好像没有遇到, 看一下代码?

**Comment by lizhuoyuan** [comment]
没有回复就先关掉 了
 有问题再开
